name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  pull_request:

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  build:
    uses: portapps/.github/.github/workflows/app-build.yml@master
    
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get release info
        id: release_info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=$(echo $TAG_NAME | cut -d'-' -f1)
          RELEASE=$(echo $TAG_NAME | cut -d'-' -f2)
          
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "release=$RELEASE" >> $GITHUB_OUTPUT
          
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/
          
      - name: List artifacts
        run: |
          echo "Available artifacts:"
          find ./artifacts/ -type f -name "*.zip" -o -name "*.exe" | head -20
          
      - name: Create Release
        run: |
          # Find artifact files
          ARTIFACT_FILES=$(find ./artifacts/ -type f -name "*.zip" -o -name "*.exe" | tr '\n' ' ')
          
          if [ -z "$ARTIFACT_FILES" ]; then
            echo "ERROR: No artifact files found!"
            echo "Available files:"
            find ./artifacts/ -type f | head -20
            exit 1
          fi
          
          echo "Creating release with artifacts: $ARTIFACT_FILES"
          
          gh release create "${{ steps.release_info.outputs.tag_name }}" \
            --title "VS Code Portable ${{ steps.release_info.outputs.version }}" \
            --notes "## VS Code Portable ${{ steps.release_info.outputs.version }}

          Automatically updated to Visual Studio Code ${{ steps.release_info.outputs.version }}

          ### Changes
          * Updated to Visual Studio Code ${{ steps.release_info.outputs.version }}
          * Latest bug fixes and security updates from Microsoft
          * Portapps 3.16.0 framework

          ### Download
          Download the portable application from the assets below:
          - **vscode-portable-${{ steps.release_info.outputs.version }}-${{ steps.release_info.outputs.release }}-win64.zip** - Main portable application
          - **vscode-portable-${{ steps.release_info.outputs.version }}-${{ steps.release_info.outputs.release }}-win64.exe** - Installer version

          ### Installation
          1. Download the ZIP file
          2. Extract to your desired location
          3. Run vscode-portable.exe to start Visual Studio Code
          
          ### Notes
          - This is a portable version that stores all settings and extensions in the application folder
          - No installation required - just extract and run
          - Fully compatible with official VS Code extensions and settings" \
            $ARTIFACT_FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
