name: Deploy GitHub Pages

on:
  release:
    types: [published]
  workflow_dispatch:
  schedule:
    # Update pages daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_run:
    workflows: ["build"]
    types: [completed]
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-page:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Download latest build artifacts
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          name: vscode-portable-artifacts
          path: ./latest-artifacts/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Generate release page
        run: |
          mkdir -p docs
          
          # Create index.html
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>VS Code Portable - Downloads</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      max-width: 1200px;
                      margin: 0 auto;
                      padding: 20px;
                      background-color: #f6f8fa;
                  }
                  .header {
                      text-align: center;
                      margin-bottom: 40px;
                      padding: 40px 0;
                      background: linear-gradient(135deg, #007acc, #0056b3);
                      color: white;
                      border-radius: 10px;
                  }
                  .header h1 {
                      margin: 0;
                      font-size: 2.5em;
                  }
                  .header p {
                      margin: 10px 0 0 0;
                      font-size: 1.2em;
                      opacity: 0.9;
                  }
                  .release-card {
                      background: white;
                      border-radius: 10px;
                      padding: 30px;
                      margin: 20px 0;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                      border: 1px solid #e1e4e8;
                  }
                  .release-title {
                      font-size: 1.8em;
                      margin-bottom: 15px;
                      color: #24292e;
                  }
                  .release-date {
                      color: #586069;
                      font-size: 0.9em;
                      margin-bottom: 20px;
                  }
                  .download-buttons {
                      display: flex;
                      gap: 15px;
                      flex-wrap: wrap;
                      margin: 20px 0;
                  }
                  .download-btn {
                      display: inline-flex;
                      align-items: center;
                      background: #007acc;
                      color: white;
                      text-decoration: none;
                      padding: 12px 24px;
                      border-radius: 6px;
                      font-weight: 500;
                      transition: background-color 0.2s;
                  }
                  .download-btn:hover {
                      background: #0056b3;
                  }
                  .download-btn::before {
                      content: '⬇️';
                      margin-right: 8px;
                  }
                  .info-section {
                      background: #f1f8ff;
                      padding: 20px;
                      border-radius: 6px;
                      margin: 20px 0;
                      border-left: 4px solid #007acc;
                  }
                  .info-section h3 {
                      margin-top: 0;
                      color: #0366d6;
                  }
                  .badges {
                      text-align: center;
                      margin: 20px 0;
                  }
                  .badges img {
                      margin: 0 5px;
                  }
                  .footer {
                      text-align: center;
                      margin-top: 40px;
                      padding-top: 20px;
                      border-top: 1px solid #e1e4e8;
                      color: #586069;
                  }
                  .loading {
                      text-align: center;
                      padding: 40px;
                      color: #586069;
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>🚀 VS Code Portable</h1>
                  <p>Visual Studio Code portable application for Windows - No installation required!</p>
              </div>

              <div class="badges">
                  <img src="https://img.shields.io/github/release/hungpv-fs/vscode-portable.svg?style=flat-square" alt="GitHub release">
                  <img src="https://img.shields.io/github/downloads/hungpv-fs/vscode-portable/total.svg?style=flat-square" alt="Total downloads">
                  <img src="https://img.shields.io/github/workflow/status/hungpv-fs/vscode-portable/build?label=build&logo=github&style=flat-square" alt="Build Status">
              </div>

              <div class="info-section">
                  <h3>🎯 What is VS Code Portable?</h3>
                  <p>VS Code Portable is a portable version of Microsoft's Visual Studio Code editor that runs without installation. All settings, extensions, and data are stored within the application folder, making it perfect for:</p>
                  <ul>
                      <li>Running from USB drives or external storage</li>
                      <li>Using on computers where you can't install software</li>
                      <li>Keeping multiple isolated VS Code environments</li>
                      <li>Development environments that need to be easily portable</li>
                  </ul>
              </div>

              <div id="releases" class="loading">
                  <p>Loading releases...</p>
              </div>

              <div class="info-section">
                  <h3>📋 How to Use</h3>
                  <ol>
                      <li>Download the latest release ZIP file from above</li>
                      <li>Extract the ZIP file to your desired location</li>
                      <li>Run <code>vscode-portable.exe</code> to start Visual Studio Code</li>
                      <li>Your settings and extensions will be stored in the app folder</li>
                  </ol>
              </div>

              <div class="info-section">
                  <h3>🔄 Builds & Releases</h3>
                  <p>This project provides VS Code Portable in two ways:</p>
                  <ul>
                      <li><strong>🚀 Development Builds:</strong> Created automatically on every code change. Get the latest features immediately but may be less stable.</li>
                      <li><strong>📋 Stable Releases:</strong> Official releases created when new VS Code versions are available. These are thoroughly tested and recommended for production use.</li>
                  </ul>
                  <p>Both types are shown above - development builds are highlighted in green/blue borders.</p>
              </div>

              <div class="info-section">
                  <h3>🔄 Automatic Updates</h3>
                  <p>This repository automatically checks for new VS Code releases twice weekly (Sunday and Wednesday at midnight UTC) and creates updated portable versions with the latest features and security fixes.</p>
              </div>

              <div class="footer">
                  <p>
                      Made with ❤️ using <a href="https://portapps.io">Portapps</a> framework<br>
                      Not affiliated with Microsoft Corporation<br>
                      <a href="https://github.com/hungpv-fs/vscode-portable">View on GitHub</a>
                  </p>
              </div>

              <script>
                  async function loadReleases() {
                      try {
                          const response = await fetch('https://api.github.com/repos/hungpv-fs/vscode-portable/releases');
                          const releases = await response.json();
                          
                          const releasesContainer = document.getElementById('releases');
                          releasesContainer.innerHTML = '';
                          
                          // Add latest build artifacts section if available
                          const latestArtifacts = await loadLatestArtifacts();
                          if (latestArtifacts) {
                              releasesContainer.appendChild(latestArtifacts);
                          }
                          
                          if (releases.length === 0) {
                              const noReleases = document.createElement('div');
                              noReleases.innerHTML = '<p>No stable releases available yet.</p>';
                              releasesContainer.appendChild(noReleases);
                              return;
                          }
                          
                          releases.slice(0, 5).forEach(release => {
                              const releaseCard = document.createElement('div');
                              releaseCard.className = 'release-card';
                              
                              const downloadButtons = release.assets.map(asset => 
                                  `<a href="${asset.browser_download_url}" class="download-btn">
                                      ${asset.name} <span style="font-size: 0.8em; opacity: 0.8;">(${(asset.size / 1024 / 1024).toFixed(1)} MB)</span>
                                  </a>`
                              ).join('');
                              
                              releaseCard.innerHTML = `
                                  <div class="release-title">${release.name}</div>
                                  <div class="release-date">Released: ${new Date(release.published_at).toLocaleDateString()}</div>
                                  <div class="download-buttons">
                                      ${downloadButtons}
                                  </div>
                                  <div style="margin-top: 15px;">
                                      <details>
                                          <summary style="cursor: pointer; color: #0366d6;">Release Notes</summary>
                                          <div style="margin-top: 10px; padding: 10px; background: #f8f9fa; border-radius: 4px;">
                                              ${release.body ? release.body.replace(/\n/g, '<br>') : 'No release notes available.'}
                                          </div>
                                      </details>
                                  </div>
                              `;
                              
                              releasesContainer.appendChild(releaseCard);
                          });
                      } catch (error) {
                          console.error('Error loading releases:', error);
                          document.getElementById('releases').innerHTML = 
                              '<p>Error loading releases. Please visit the <a href="https://github.com/hungpv-fs/vscode-portable/releases">GitHub releases page</a> directly.</p>';
                      }
                  }
                  
                  async function loadLatestArtifacts() {
                      try {
                          // Check if we have workflow run data (triggered by build completion)
                          const urlParams = new URLSearchParams(window.location.search);
                          const workflowRun = urlParams.get('workflow_run');
                          
                          if (workflowRun) {
                              const workflowResponse = await fetch(`https://api.github.com/repos/hungpv-fs/vscode-portable/actions/runs/${workflowRun}`);
                              const workflowData = await workflowResponse.json();
                              
                              if (workflowData.conclusion === 'success') {
                                  const artifactsResponse = await fetch(`https://api.github.com/repos/hungpv-fs/vscode-portable/actions/runs/${workflowRun}/artifacts`);
                                  const artifactsData = await artifactsResponse.json();
                                  
                                  const vscodeArtifacts = artifactsData.artifacts.filter(artifact => 
                                      artifact.name === 'vscode-portable-artifacts'
                                  );
                                  
                                  if (vscodeArtifacts.length > 0) {
                                      const latestCard = document.createElement('div');
                                      latestCard.className = 'release-card';
                                      latestCard.style.border = '2px solid #28a745';
                                      latestCard.style.backgroundColor = '#f8fff8';
                                      
                                      latestCard.innerHTML = `
                                          <div class="release-title">🚀 Latest Build (Development)</div>
                                          <div class="release-date">Built: ${new Date(workflowData.updated_at).toLocaleDateString()}</div>
                                          <div style="margin: 15px 0; padding: 10px; background: #d4edda; border-radius: 4px; color: #155724;">
                                              <strong>⚠️ Development Build:</strong> This is the latest development build from the main branch. 
                                              While it includes the newest features and updates, it may be less stable than official releases.
                                          </div>
                                          <div class="download-buttons">
                                              <a href="https://github.com/hungpv-fs/vscode-portable/actions/runs/${workflowRun}" class="download-btn">
                                                  View Build Details & Download Artifacts
                                              </a>
                                          </div>
                                      `;
                                      
                                      return latestCard;
                                  }
                              }
                          }
                          
                          // Fallback: check for latest workflow run
                          const workflowsResponse = await fetch('https://api.github.com/repos/hungpv-fs/vscode-portable/actions/workflows/build.yml/runs?status=success&per_page=1');
                          const workflowsData = await workflowsResponse.json();
                          
                          if (workflowsData.workflow_runs && workflowsData.workflow_runs.length > 0) {
                              const latestRun = workflowsData.workflow_runs[0];
                              
                              const latestCard = document.createElement('div');
                              latestCard.className = 'release-card';
                              latestCard.style.border = '2px solid #007acc';
                              latestCard.style.backgroundColor = '#f8f9ff';
                              
                              latestCard.innerHTML = `
                                  <div class="release-title">📦 Latest Successful Build</div>
                                  <div class="release-date">Built: ${new Date(latestRun.updated_at).toLocaleDateString()}</div>
                                  <div style="margin: 15px 0; padding: 10px; background: #cce5ff; border-radius: 4px; color: #0c5aa6;">
                                      <strong>ℹ️ Latest Build:</strong> This represents the most recent successful build. 
                                      Download artifacts to get the latest version with newest features.
                                  </div>
                                  <div class="download-buttons">
                                      <a href="https://github.com/hungpv-fs/vscode-portable/actions/runs/${latestRun.id}" class="download-btn">
                                          View Build & Download Artifacts
                                      </a>
                                  </div>
                              `;
                              
                              return latestCard;
                          }
                          
                          return null;
                      } catch (error) {
                          console.error('Error loading latest artifacts:', error);
                          return null;
                      }
                  }
                  
                  loadReleases();
              </script>
          </body>
          </html>
          EOF
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4